version: '3'

services:
  spring-boot-app:
    image: luthorhub/online-public-libraries:1.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: online_public_libraries
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
