###Get all libraries
GET http://localhost:8080/api/libraries

### FindById
GET http://localhost:8080/api/libraries/2

###Create new library
POST http://localhost:8080/api/libraries
Content-Type: application/json

{
   "name": "Hammanskrall Public Library",
   "location": "Pretoria North",
  "openingHours": [
    {
      "dayOfWeek": "MONDAY",
      "openingHours": "09:00",
      "closingHours": "17:00"
    },
    {
      "dayOfWeek": "TUESDAY",
      "openingHours": "09:00",
      "closingHours": "17:00"
    }
  ,
    {
      "dayOfWeek": "WEDNESDAY",
      "openingHours": "09:00",
      "closingHours": "17:00"
    }
  , {
      "dayOfWeek": "THURSDAY",
      "openingHours": "09:00",
      "closingHours": "17:00"
    }
  , {
      "dayOfWeek": "FRIDAY",
      "openingHours": "09:00",
      "closingHours": "17:00"
    }
  , {
      "dayOfWeek": "SATURDAY",
      "openingHours": "11:00",
      "closingHours": "15:30"
    }
  ]
}

### Update library and its artefacts
PUT http://localhost:8080/api/libraries
Content-Type: application/json

{
  "id": 2,
  "name": "Hammanskraal Public Library",
  "location": "Pretoria North",
  "bookList": null,
  "openingHours": [
    {
      "id": 3,
      "library_id": 2,
      "dayOfWeek": "MONDAY",
      "openingHours": "09:00",
      "closingHours": "17:00"
    },
    {
      "id": 4,
      "library_id": 2,
      "dayOfWeek": "TUESDAY",
      "openingHours": "09:00",
      "closingHours": "17:00"
    },
    {
      "id": 5,
      "library_id": 2,
      "dayOfWeek": "WEDNESDAY",
      "openingHours": "09:00",
      "closingHours": "17:00"
    },
    {
      "id": 6,
      "library_id": 2,
      "dayOfWeek": "THURSDAY",
      "openingHours": "09:00",
      "closingHours": "17:00"
    },
    {
      "id": 7,
      "library_id": 2,
      "dayOfWeek": "FRIDAY",
      "openingHours": "09:00",
      "closingHours": "17:00"
    },
    {
      "id": 8,
      "library_id": 2,
      "dayOfWeek": "SATURDAY",
      "openingHours": "11:00",
      "closingHours": "15:30"
    },
    {
      "library_id": 2,
      "dayOfWeek": "SUNDAY",
      "openingHours": "13:00",
      "closingHours": "16:30"
    }
  ]
}

###Delete Library and all its resources
### FindById
DELETE http://localhost:8080/api/libraries/2


